apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"  # pour que métallb utilise une ip pour tout les services
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 21
    name: ftps
  - port: 20
    name: ftps-20
  - port: 30000
    name: ftps-30000
  - port: 30001
    name: ftps-30001

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000
        - containerPort: 30001
        env:
        - name: USER
          value: root
        - name: PASSWORD
          value: password