apiVersion: v1 #version de l'API k8s qui prend en charge le concept des ReplicasSets.
kind: Service ##nous créons un objet Kubernetes de type Service. 
metadata:
  name: mysql
  labels:
    app: wordpress ## nous indiquons que le service wordpress ne sera utilisé que par les Pods ayant le label app: wordpress.
spec:
  ports:
    - port: 3306 #le port est le numéro de port qui sera utilisé par notre service
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: my_mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim