apiVersion: apps/v1 #apps/v1 qui est la version de l'API k8s qui prend en charge le concept des ReplicasSets. 
kind: Deployment #nous créons un objet Kubernetes de type Deployment. 
metadata: #données de type clé valeur permettant d’identifier de manière unique l’objet.
  name: nginx-deployment #nom du POD
  labels:
    app: nginx-app
spec: #contient la spécification avec des champs imbriqués propres à chaque objet k8S.
  replicas: 1 #nombre de replique
  selector:
    matchLabels:
      app: nginx-app #consiste à répliquer les pods ayant le label app: nginx-app. 
  template:
    metadata:
      labels:
        app: nginx-app
    spec: #contient la spécification avec des champs imbriqués propres à chaque objet k8S.
      containers:
      - name: nginx #nom du conteneur
        image: my_nginx #nom de l'image
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer #le type de notre service. 
  ports:
  - name: http
    port: 80 #le port est le numéro de port qui sera utilisé par notre service afin de communiquer avec lui depuis l'intérieur de notre cluster K8. 
    targetPort: 80 # le targetPort est le port qui est utilisé par les Pods de notre Deployment
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: nginx-app # nous indiquons que le service nginx-app ne sera utilisé que par les Pods ayant le label app: nginx-app. 