apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: mysql
    spec:
      containers:
      - name: phpmyadmin
        image: my_phpmyadmin
        ports:
          - containerPort: 5000
            name: phpmyadmin
        env:
          - name: PMA_HOST
            value: mysql
          - name: PMA_PORT
            value: "3306"
          - name: PMA_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: password
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 20

---

  apiVersion: v1
  kind: Service
  metadata:
    name: phpmyadmin
    annotations:
      metallb.universe.tf/allow-shared-ip: "true"   # pour que métallb utilise une ip pour tout les services 
    labels:
      app: phpmyadmin
  spec:
    ports:
      - port: 5000
        targetPort: 5000
        protocol: TCP
        name: phpmyadmin
    selector:
      app: phpmyadmin
      tier: mysql
    type: LoadBalancer