FROM alpine:3.11

RUN apk update \
 && apk add nginx openssl 

RUN	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/example.key -out /etc/nginx/example.crt -subj "/C=FR/ST=IDE/L=Paris/O=42/OU=42/CN=mywebsite.com" 

RUN mkdir -p /run/nginx

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./index_nginx.html /www/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]